name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment-pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies for backend
        run: npm install
      - name: Install dependencies for frontend
        working-directory: ./client
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build client
        working-directory: ./client
        run: npm run build
      - name: Unit test backend
        run: npm run test
      - name: Unit test frontend
        working-directory: ./client
        run: npm run test
      - name: E2E test
        uses: cypress-io/github-action@v6
        with:
          start: npm run start-prod
          wait-on: http://localhost:5000